repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      - id: ruff-format
        name: ruff format
        exclude: "^notebooks/"
      - id: ruff
        name: ruff check
        args: [--fix]
        exclude: "^notebooks/"

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: uv run pyright src/
        language: system
        types: [python]
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: env -u GIT_DIR -u GIT_WORK_TREE uv run pytest
        language: system
        types: [python]
        pass_filenames: false
        stages: [commit]
