#!/usr/bin/env python3
"""generate_graph — derive workflows/graph.yml from artifact meta.yml files.

Each meta.yml has:
    artifact:
      id: <slug>
    relationships:
      informs: [<slug>, ...]

We walk workflows/activities/<NN-name>/artifacts/<type>/meta.yml, emit one node
per type and one edge per informs entry. The result is the canonical mainline
graph the helix routing skill consults at authoring time
(see skills/helix/SKILL.md §"Consult The Graph Before Authoring").

Single source of truth: edit meta.yml, regenerate graph.yml. Drift between the
two is a validate-skills.sh failure.
"""

from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print(
        "error: PyYAML required (uv run --with pyyaml scripts/generate_graph.py)",
        file=sys.stderr,
    )
    sys.exit(2)


REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOG = REPO_ROOT / "workflows" / "activities"
OUT = REPO_ROOT / "workflows" / "graph.yml"


def collect():
    activities = []
    nodes = []
    edges = []
    seen_ids = set()

    for activity_dir in sorted(CATALOG.iterdir()):
        if not activity_dir.is_dir() or not activity_dir.name[:2].isdigit():
            continue
        activities.append({"id": activity_dir.name})

        artifacts_dir = activity_dir / "artifacts"
        if not artifacts_dir.is_dir():
            continue

        for type_dir in sorted(artifacts_dir.iterdir()):
            meta_path = type_dir / "meta.yml"
            if not meta_path.is_file():
                continue
            meta = yaml.safe_load(meta_path.read_text()) or {}
            art = meta.get("artifact", {})
            slug = art.get("id") or type_dir.name
            if slug in seen_ids:
                print(
                    f"warn: duplicate artifact id {slug} ({meta_path})", file=sys.stderr
                )
                continue
            seen_ids.add(slug)
            nodes.append(
                {
                    "id": slug,
                    "type": f"library:{slug}",
                    "activity": activity_dir.name,
                    "cardinality": "many",
                }
            )

            for target in (meta.get("relationships") or {}).get("informs") or []:
                edges.append(
                    {
                        "from": slug,
                        "to": target,
                        "kind": "informs",
                        "required": False,
                    }
                )

    # Drop edges whose target isn't a known node (avoids broken refs).
    valid_targets = {n["id"] for n in nodes}
    pruned = [e for e in edges if e["to"] in valid_targets]
    dropped = [e for e in edges if e["to"] not in valid_targets]
    return activities, nodes, pruned, dropped


def main() -> int:
    activities, nodes, edges, dropped = collect()

    if dropped:
        print(
            f"warn: dropped {len(dropped)} edges with unknown targets:", file=sys.stderr
        )
        for e in dropped:
            print(f"  {e['from']} -> {e['to']}", file=sys.stderr)

    graph = {
        "version": 1,
        "methodology": {
            "id": "helix",
            "library_version": "^1.0.0",
            "validator_contract": 1,
        },
        "activities": activities,
        "nodes": nodes,
        "edges": edges,
        "allowed_cycles": [],
        "external_edges": [],
    }

    header = (
        "# workflows/graph.yml — canonical HELIX product graph (single-flow plugin).\n"
        "#\n"
        "# GENERATED by scripts/generate_graph.py from workflows/activities/*/artifacts/*/meta.yml.\n"
        "# Edit meta.yml `relationships.informs:` blocks, then regenerate with:\n"
        "#   python3 scripts/generate_graph.py\n"
        "#\n"
        "# Consumed by:\n"
        '#   - skills/helix/SKILL.md §"Consult The Graph Before Authoring" — the runtime\n'
        "#     reads this graph at authoring time to surface prerequisites.\n"
        "#   - tests/validate-skills.sh — asserts file is present + edges round-trip\n"
        "#     against meta.yml.\n"
    )
    body = yaml.safe_dump(graph, sort_keys=False, default_flow_style=False, indent=2)
    OUT.write_text(header + body)
    print(
        f"wrote {OUT.relative_to(REPO_ROOT)}: "
        f"{len(activities)} activities, {len(nodes)} nodes, {len(edges)} edges"
        + (f", dropped {len(dropped)} dangling" if dropped else "")
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
