"""Run-selectable domain packs; registration never changes the default pack."""

from dataclasses import dataclass
from copy import deepcopy
import json
from pathlib import Path
from typing import Any, Callable, cast

from tablespec.inference.domain_types import DomainTypeRegistry

from .generators import HealthcareDataGenerators
from .legal import LegalDataGenerators, LEGAL_PACK, LEGAL_TYPES


@dataclass(frozen=True)
class DomainPack:
    """Bind a value-generator factory to its matching domain-type registry."""

    generators: Callable[..., Any]
    registry: Callable[[], DomainTypeRegistry]
    metadata: dict[str, Any] | None = None


_PACKS = {
    "healthcare": DomainPack(HealthcareDataGenerators, DomainTypeRegistry),
    "legal": DomainPack(
        LegalDataGenerators,
        lambda: DomainTypeRegistry(registry_data={"domain_types": LEGAL_TYPES}),
        LEGAL_PACK,
    ),
}

# Trusted implementations are installed by application code, never by metadata.
_GENERATOR_FACTORIES: dict[tuple[str, str], Callable[..., Any]] = {
    ("tablespec.legal", "1.0.0"): LegalDataGenerators,
    ("tablespec.healthcare", "1.0.0"): HealthcareDataGenerators,
}


def register_generator_factory(
    identifier: str, version: str, factory: Callable[..., Any]
) -> None:
    """Install trusted executable code explicitly for an exact metadata reference."""
    key = (identifier, version)
    if not identifier or not version or key in _GENERATOR_FACTORIES:
        raise ValueError("Generator identity is empty or already registered")
    if not callable(factory):
        raise ValueError("Generator implementation must be callable")
    _GENERATOR_FACTORIES[key] = factory


def read_domain_pack(path: Path) -> dict[str, Any]:
    """Consume UMF-owned metadata using a shipped generated schema snapshot.

    domain_pack.schema.json is generated by UMF's domain-pack-schema.ts, not
    authored here. Artifact references are retained but never fetched. Generator
    IDs resolve only against the explicitly installed implementations above.
    """
    from umf import read_json_value, schema_validator

    metadata = read_json_value(path.read_text(encoding="utf-8"))
    schema = json.loads(Path(__file__).with_name("domain_pack.schema.json").read_text())
    errors = list(schema_validator(schema).iter_errors(metadata))
    if errors:
        raise ValueError("Invalid UMF domain-pack metadata")
    metadata = cast(dict[str, Any], metadata)
    schemas = [item["id"] for item in metadata.get("schemas", [])]
    if len(schemas) != len(set(schemas)):
        raise ValueError("Duplicate domain-pack schema identity")
    for binding in metadata.get("source_bindings", []):
        if binding["schema_id"] not in schemas or binding[
            "source_id"
        ] not in metadata.get("sources", {}):
            raise ValueError("Unresolved domain-pack source binding")
    return metadata


def load_domain_pack(path: Path) -> DomainPack:
    """Resolve synthetic generation only through installed implementations.

    External/mixed row inputs need an explicit ingestion adapter; they never
    silently fall back to generated rows. Reference and terminology sources
    remain declared metadata and are not downloaded.
    """
    metadata = read_domain_pack(path)
    if "generator" not in metadata or any(
        binding["role"] == "rows"
        and metadata["sources"][binding["source_id"]]["kind"] == "external"
        for binding in metadata.get("source_bindings", [])
    ):
        raise ValueError(
            "Externally sourced rows require explicit ingestion; generation is refused"
        )
    reference = metadata["generator"]
    if set(reference) - {"id", "version"}:
        raise ValueError("Unsupported generator execution metadata")
    factory = _GENERATOR_FACTORIES.get((reference["id"], reference["version"]))
    if factory is None:
        raise ValueError(
            "Domain pack references an unregistered generator implementation"
        )
    for definition in metadata["domain_types"].values():
        generation = definition.get("sample_generation", {})
        if set(generation) - {"method"}:
            raise ValueError("Unsupported sample-generation execution metadata")
        method = generation.get("method")
        if method and not callable(getattr(factory, method, None)):
            raise ValueError("Domain pack references an unsupported generator method")
    return DomainPack(
        factory,
        lambda: DomainTypeRegistry(
            registry_data={"domain_types": deepcopy(metadata["domain_types"])}
        ),
        deepcopy(metadata),
    )


def get_run_domain_pack(config: Any) -> DomainPack:
    """Resolve explicit per-run metadata without changing built-in registration."""
    if config.domain_pack_path is None:
        return get_domain_pack(config.domain)
    pack = load_domain_pack(config.domain_pack_path)
    if pack.metadata is None or pack.metadata["id"] != config.domain:
        raise ValueError("Domain pack id must match the selected domain")
    return pack


def register_domain_pack(name: str, pack: DomainPack) -> None:
    """Register an application pack explicitly; reject accidental replacement."""
    if not name or name in _PACKS:
        raise ValueError(f"Domain pack already registered or empty: {name}")
    _PACKS[name] = pack


def get_domain_pack(name: str) -> DomainPack:
    """Resolve a pack, failing before generation on unknown names."""
    try:
        return _PACKS[name]
    except KeyError as exc:
        raise ValueError(
            f"Unknown domain pack {name}; choose from {sorted(_PACKS)}"
        ) from exc
